// Package dto defines Data Transfer Objects used for HTTP requests and responses.
package dto

// CreateChatSessionsRequest represents the payload sent by the frontend
// to initialize a new chat session. It optionally includes vehicle context.
type CreateChatSessionsRequest struct {
	// VehicleBrand in the brand of the vehicle provided by the user (optional).
	VehicleBrand string `json:"vehicle_brand"`

	// VehicleModel is the model of the vehicle provided by the user (optional).
	VehicleModel string `json:"vehicle_model"`

	// VehicleYear is the year of the vehicle provided by the user (optional).
	VehicleYear string `json:"vehicle_year"`
}

// SendChatMessageRequest represents the payload sent by the frontend
// when a user sends a new text message to the chat.
type SendChatMessageRequest struct {
	// Text is the content of the messafe sent by the user.
	// This field is required.
	Text string `json:"text" binding:"required"`
}

// ChatMessageResponse represents a chat session formatted for the frontend.
type ChatMessageResponse struct {
	// ID is the unique identifier of the message.
	ID uint `json:"id"`

	// Role indicates if the message is from the "user" or "assistant".
	Role string `json:"role"`

	// Content is the actual text of the message.
	Content string `json:"content"`

	// CreatedAt is the timestamp of the message formatted as a string.
	CreatedAt string `json:"created_at"`
}

// ChatSessionResponse represents a chat session formatted for the frontend.
// It includes the vehicle context and optionally the message history.
type ChatSessionResponse struct {
	// ID is the unique identifier of the chat session.
	ID uint `json:"id"`

	// Status is the current state of the session (e.g., "need_info")
	Status string `json:"status"`

	// VehicleBrand is the stored vehicle brand.
	VehicleBrand string `json:"vehicle_brand"`

	// VehicleModel is the stored vehicle model.
	VehicleModel string `json:"vehicle_model"`

	// VehicleYear is the stored vehicle year.
	VehicleYear string `json:"vehicle_year"`

	// CreatedAt is the session creation timestamp formatted as a string.
	CreatedAt string `json:"created_at"`

	// Messages contains the chat history associated with this session.
	// It is omitted from the JSON response if empty.
	Messages []ChatMessageResponse `json:"messages,omitempty"`
}

// ChatSyncResponse represents the structured synchronous response returned
// to the frontend after a user sends a message.
type ChatSyncResponse struct {
	// UserMessage is the confirmed message sent by the user.
	UserMessage ChatMessageResponse `json:"user_message"`

	// AssistantMessage is the reply generated by the AI assistant.
	AssistantMessage ChatMessageResponse `json:"assistantMessage"`

	// Session contains the updated chat session state and context.
	Session ChatSessionResponse `json:"session"`
}
