// Package repository handles all database operations for business entities.
package repository

import (
	"errors"
	"fmt"

	"github.com/isw2-unileon/proyect-scaffolding/backend/internal/models"
	"gorm.io/gorm"
)

// OrdersRepository defines the interface for order data operations.
// Using an interface allows us to mock the repository in tests.
type OrdersRepository interface {
	// FindAll retrieves all orders form the database.
	FindAll() ([]models.Order, error)

	// FindByID retrieves a single order by its ID.
	// Returns an error if the order is not found.
	FindByID(id uint) (*models.Order, error)

	// Create inserts a new order into the database.
	// Returns the created order with its generated ID.
	Create(order *models.Order) (*models.Order, error)

	// UpdateStatus changes the status of an order.
	UpdateStatus(id uint, status models.OrderStatus) (*models.Order, error)

	// Delete removes an order form the database by ID.
	// Returns an error if the order does not exist.
	Delete(id uint) error
}

// ordersRepositoryImpl is the concrete implementation of OrdersRepository using GORM.
type ordersRepositoryImpl struct {
	db *gorm.DB
}

// NewOrdersRepository creates a new instance of the orders repository.
// It accepts a GORM database connection and returns and OrdersRepository interface.
func NewOrdersRepository(db *gorm.DB) OrdersRepository {
	return &ordersRepositoryImpl{
		db: db,
	}
}

// FindAll retrieves all orders from the database with their associated items.
// Returns an empty slice if no orders are found (not an error).
func (r *ordersRepositoryImpl) FindAll() ([]models.Order, error) {
	var orders []models.Order

	// Query all orders and preload their order items and parts.
	if err := r.db.Preload("OrderItems").Preload("OrderItems.Part").Find(&orders).Error; err != nil {
		return nil, fmt.Errorf("failed to fetch orders: %w", err)
	}

	// Return empty slice instead of nil for JSON consistency.
	if orders == nil {
		orders = []models.Order{}
	}

	return orders, nil
}

// FindByID retrieves a single order by its ID with all associated items.
// Returns an error if the order does not exist.
func (r *ordersRepositoryImpl) FindByID(id uint) (*models.Order, error) {
	var order models.Order

	// Query a single order by ID and preload its items and parts.
	if err := r.db.Preload("OrderItems").Preload("OrderItems.Part").First(&order, id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("failed to fetch order with ID %d: %w", id, err)
	}
	return &order, nil
}

// Create inserts a new order into the database along with its order items.
// The order's ID and OrderItems are auto-generated by the database.
func (r *ordersRepositoryImpl) Create(order *models.Order) (*models.Order, error) {
	// Insert the order and all its order items in a transaction.
	// This ensures that either all data is saved or nothing is saved.
	if err := r.db.Create(order).Error; err != nil {
		return nil, fmt.Errorf("failed to create order: %w", err)
	}

	// Fetch the created order with its items and parts.
	return r.FindByID(order.ID)
}

// UpdateStatus changes the status of an order identified by ID.
// Returns the updated order or an error if the order does not exist.
func (r *ordersRepositoryImpl) UpdateStatus(id uint, status models.OrderStatus) (*models.Order, error) {
	// First, verify the order exists.
	if _, err := r.FindByID(id); err != nil {
		return nil, err
	}

	// Update only the status field.
	if err := r.db.Model(&models.Order{}).Where("id = ?", id).Update("status", status).Error; err != nil {
		return nil, fmt.Errorf("failed to update order status: %w", err)
	}

	// Fetch and return the updated order.
	return r.FindByID(id)
}

// Delete removes an order from the database by ID.
// This also deletes all associated order items due to the foreign key constraint.
func (r *ordersRepositoryImpl) Delete(id uint) error {
	// First, verify the order exists.
	if _, err := r.FindByID(id); err != nil {
		return err
	}

	// Delete the order and its associated items.
	if err := r.db.Delete(&models.Order{}, id).Error; err != nil {
		return fmt.Errorf("failed to delete order with ID %d: %w", id, err)
	}

	return nil
}
