// Package repository handles all database operations for business entities.
package repository

import (
	"errors"
	"fmt"

	"github.com/isw2-unileon/proyect-scaffolding/backend/internal/models"
	"gorm.io/gorm"
)

// ErrNotFound is returned when a requested entity is not un the repository.
var ErrNotFound = errors.New("entity not found")

// PartsRepository defines the interface for the part data operations.
// Using an interface allows us to mock the repository in tests.
type PartsRepository interface {
	// FindAll retrieves all parts form the database.
	FindAll(zone string, name string) ([]models.Part, error)

	// FindByID retrieves a single part by its ID.
	// Returns an error if the part is not found.
	FindByID(id uint) (*models.Part, error)

	// Create inserts a new part into the database.
	// Returns the created part with its generated ID.
	Create(part *models.Part) (*models.Part, error)

	// Update modifies an existing part by ID.
	// Only updates fields that are provided (non-nil).
	Update(id uint, updates map[string]interface{}) (*models.Part, error)

	// Delete removes a part from the database by ID.
	// Return an error if the part does not exist.
	Delete(id uint) error
}

// partsRepositoryImpl is the concrete implementation of PartsRepository using GORM.
type partsRepositoryImpl struct {
	db *gorm.DB
}

// NewPartsRepository creates a new instance of the parts repository.
// It accepts a GORM database connection and returns a PartsRepository interface.
func NewPartsRepository(db *gorm.DB) PartsRepository {
	return &partsRepositoryImpl{
		db: db,
	}
}

// FindAll retrieves all parts from the database.
// Returns an empty slice if no parts are found (not an error).
func (r *partsRepositoryImpl) FindAll(zone string, name string) ([]models.Part, error) {
	var parts []models.Part

	// Build query with optional filters.
	query := r.db

	// Filters by zone if provided.
	if zone != "" {
		query = query.Where("car_zone = ?", zone)
	}

	// Search by name if provided (case-insensitive).
	if name != "" {
		query = query.Where("LOWER(name) LIKE LOWER(?)", "%"+name+"%")
	}

	// Execute the query.
	if err := query.Find(&parts).Error; err != nil {
		return nil, fmt.Errorf("failed to fetch parts: %w", err)
	}

	// Return empty slice instead of nil for JSON consistency.
	if parts == nil {
		parts = []models.Part{}
	}

	return parts, nil
}

// FindByID retrieves a single part by its ID.
// Returns gorm.ErrRecordNotFound if the part does not exist.
func (r *partsRepositoryImpl) FindByID(id uint) (*models.Part, error) {
	var part models.Part

	// Query a single part by ID.
	if err := r.db.First(&part, id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("failed to fetch part with ID %d: %w", id, err)
	}

	return &part, nil
}

// Create inserts a new part into the database.
// The part's ID is auto-generated by the database.
// Returns the created part with its new ID.
func (r *partsRepositoryImpl) Create(part *models.Part) (*models.Part, error) {
	// Insert the part into the database.
	// GORM's Create method sets the ID on the struct after insertion.
	if err := r.db.Create(part).Error; err != nil {
		return nil, fmt.Errorf("failed to creare part: %w", err)
	}

	return part, nil
}

// Update modifies an existing part identified by ID.
// The updates parameter is a map of field names to new values.
// This allows partial updates (e.g., update only the price).
func (r *partsRepositoryImpl) Update(id uint, updates map[string]interface{}) (*models.Part, error) {
	// First, check if the part exists.
	existingPart, err := r.FindByID(id)
	if err != nil {
		return nil, err
	}

	// Update only the provided fields.
	// Using Updates() with a map is more flexible than saving the entire struct.
	if err := r.db.Model(existingPart).Updates(updates).Error; err != nil {
		return nil, fmt.Errorf("failed to update part with ID %d: %w", id, err)
	}

	// Fetch the updated part to return fresh data from the database.
	return r.FindByID(id)
}

// Delete removes a part from the database by ID.
// Returns an error if the part does not exist.
func (r *partsRepositoryImpl) Delete(id uint) error {
	// First, verify the part exists.
	if _, err := r.FindByID(id); err != nil {
		return err
	}

	// Delete the part by ID.
	if err := r.db.Delete(&models.Part{}, id).Error; err != nil {
		return fmt.Errorf("failed to delete part with ID %d: %w", id, err)
	}

	return nil
}
